set-option -g default-shell /bin/zsh
set -g mouse on
set-option -g mouse on
set -g default-terminal "screen-256color"
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi y send-keys -X copy-selection

# This makes osc52 copy work properly over ssh
set -g set-clipboard on
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"

# Reduce Vim escape lag
set -sg escape-time 0

# Set prefix to Ctrl-b
unbind C-a
set -g prefix C-b
bind C-b send-prefix
