set-option -g default-shell /bin/zsh
set -g mouse on
set-option -g mouse on
set -g default-terminal "screen-256color"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection

# # This makes osc52 copy work properly over ssh
# set -g set-clipboard on
# set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"

## clipboard setup
# So that you can copy by selecting text with mouse
set -s set-clipboard on
set -g mouse on
# Include the character under the cursor when selecting with mouse
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X cursor-right \; send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X cursor-right \; send-keys -X copy-selection-and-cancel

### first way: let tmux handle setting clipboard with osc52
### depending on tmux version one of these may be needed
# set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"
# set -as terminal-features ',rxvt-unicode-256color:clipboard'

### second way: use an external tool to set clipboard, anything you can use like
###`echo stuff | some command`. The tool here is from https://github.com/theimpostor/osc
# set -g allow-passthrough all
set -g copy-command 'osc copy'


# Reduce Vim escape lag
set -sg escape-time 0

# Set prefix to Ctrl-b
unbind C-a
set -g prefix C-b
bind C-b send-prefix
