" Don't try to be vi compatible
set nocompatible

" Helps force plugins to load correctly when it is turned back on below
filetype off

" ##################### Plugins ###############################
" Vim-plug section: Add plugins here, reload .vimrc with ':so %', then run
" ':PlugInstall'.
call plug#begin('~/.vim/plugged')
" Plug 'tpope/vim-fugitive'           " git integration

Plug 'ojroques/vim-oscyank'
"Plug 'altercation/vim-colors-solarized' " Colorscheme
Plug 'yous/vim-open-color' " Colorscheme
Plug 'itchyny/lightline.vim'        " statusbar
" Set lightline colorscheme
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }



" Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }         " sidebar file tree view
Plug 'tpope/vim-fugitive'

Plug 'lervag/vimtex', {'for': 'tex'}                " LaTeX integration
Plug 'eigenfoo/stan-vim'
Plug 'mzlogin/vim-markdown-toc'
" LaTeX settings
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='amgs'
if has('nvim')
let g:vimtex_compiler_progname = 'nvr'
endif

Plug 'tpope/vim-commentary'         " Comment and uncomment, 'gcc'

" Plug 'sirver/ultisnips'
" let g:UltiSnipsExpandTrigger = '<tab>'
" let g:UltiSnipsJumpForwardTrigger = '<tab>'
" let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
" let g:UltiSnipsSnippetsDir = "~/.vim/UltiSnips"

Plug 'tmsvg/pear-tree'              " Auto-close brackets
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1
let g:pear_tree_pairs = {
            \ '(': {'closer': ')'},
            \ '[': {'closer': ']'},
            \ '{': {'closer': '}'},
            \ "'": {'closer': "'"},
            \ '"': {'closer': '"'}
            \ }

Plug 'machakann/vim-sandwich'
Plug 'sheerun/vim-polyglot'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'ayu-theme/ayu-vim'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'vim-pandoc/vim-rmarkdown'
" Plug 'gabrielelana/vim-markdown' 
call plug#end()
" ###################### End Plugins ################

" Turn on syntax highlighting
syntax enable
highlight Comment cterm=italic
" Allow italics to display on mac
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

" For plugins to load correctly
filetype plugin indent on

" Pick a leader key
let mapleader = ","

" #################################
" Plugin Settings                 #
" #################################
" #### Plug 'tpope/vim-fugitive'           " git integration
" Plug 'ojroques/vim-oscyank'
nmap <leader>c <Plug>OSCYank
vnoremap <leader>c :OSCYANK<CR>

" #### Plug 'altercation/vim-colors-solarized' " Colorscheme
" Color scheme (terminal)
" set t_Co=256
set background=light
" let g:solarized_termcolors=256
" let g:solarized_termtrans=1

colorscheme open-color
" highlight Normal guibg=white guifg=black

" #### Plug 'scrooloose/nerdtree'          " sidebar file tree view
noremap <leader>` :NERDTreeToggle<cr>

" #### Plug 'lervag/vimtex'                " LaTeX integration

" #### Plug 'tpope/vim-commentary'         " Comment and uncomment, 'gcc'
" use ',/' to comment
noremap <leader>/ :Commentary<cr>

" #### Plug 'sirver/ultisnips'

" #### Plug 'tmsvg/pear-tree'              " Auto-close brackets



" #### Plug 'machakann/vim-sandwich'
" #### Plug 'sheerun/vim-polyglot'
" #### Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
" #### Plug 'ayu-theme/ayu-vim'
let ayucolor = 'light'
" ################## End Plugin Settings ######################


" Map ; to : in normal mode, get ; with :.
nnoremap ; :
nnoremap : ;
"; Should work normally everywhere else, including in search and commands
cnoremap ; ;

" Open Config Files
noremap <leader>erc :sp $MYVIMRC<cr>
noremap <leader>eft :sp ~/.vim/after/ftplugin/<C-R>=&filetype<CR>.vim<CR>
noremap <leader>esp :UltiSnipsEdit<cr>

" Security
set modelines=0

" Show line numbers
:set number relativenumber

" Show file stats
set ruler

" Blink cursor on error instead of beeping (grr)
set visualbell

" Encoding
set encoding=utf-8

" Whitespace
""General Setting use a tab width of 4 space chars.
set wrap
set textwidth=79
set formatoptions=cqrn1
set tabstop=4       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.
set shiftwidth=4    " Indents will have a width of 4.
set softtabstop=4   " Sets the number of columns for a TAB.
set expandtab       " Expand TABs to spaces.

" Only do this part when compiled with support for autocommands.
if has("autocmd")
    " Use filetype detection and file-based automatic indenting.
    filetype plugin indent on

    " Use actual tab chars in Makefiles.
    autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
endif

" Cursor motion
set scrolloff=3
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs
runtime! macros/matchit.vim

" Move up/down editor lines
nnoremap j gj
nnoremap k gk

" Allow hidden buffers
set hidden

" Rendering
set ttyfast

" Searching
" clear search
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
noremap <leader><space> :noh<cr>

" Remap help key.
"inoremap <F1> <ESC>:set invfullscreen<CR>a
"nnoremap <F1> :set invfullscreen<CR>
"vnoremap <F1> :set invfullscreen<CR>

" Formatting
map <leader>q gqip

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
" Uncomment this to enable by default: set list " To enable by default Or use
" your leader key + l to toggle on/off

" Toggle tabs and EOL
noremap <leader>l :set list!<CR> 

augroup BgHighlight
    autocmd!
    autocmd WinEnter * set relativenumber
    autocmd WinLeave * set norelativenumber
augroup END

" Adjust VIM status bar to remove elements given by lightline
set noshowmode
set laststatus=2
set showcmd   " Show command being typed at bottom right

set cursorline
highlight LineNr ctermbg=254
hi CursorLine ctermbg=255
hi CursorLineNr ctermbg=252 ctermfg=245 cterm=bold

set spell

" Highlight TODO
augroup HiglightTODO
    autocmd!
    autocmd WinEnter,VimEnter * :silent! call matchadd('Todo', 'TODO', -1)
augroup END


